version: '3.8'
services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
    - "8001:80"
    networks:
      - tracking-network
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/

  mysql_tracking:
    image: mysql:5.7.33
    container_name: mysql_tracking
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: tracking_api
      MYSQL_USER: tracking
      MYSQL_PASSWORD: 123456789
      MYSQL_ROOT_PASSWORD: 123456789
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql_tracking
    networks:
      - tracking-network
    volumes:
      - dbdata:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: api
    restart: unless-stopped
    depends_on:
      - mysql_tracking
      - nginx
    links:
      - mysql_tracking
    networks:
      - tracking-network
    volumes:
      - ./src:/var/www

  app:
    build:
      context: .
      dockerfile: node.dockerfile
    container_name: app
    restart: unless-stopped
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mysql_tracking
    links:
      - mysql_tracking
    networks:
      - tracking-network
    volumes:
      - ./src:/var/www

networks:
  tracking-network:
    driver: bridge

volumes:
  dbdata: